language: python
env:
  matrix:
    - TOXENV=django14-py26
    - TOXENV=django14-py27
    - TOXENV=django15-py26
    - TOXENV=django15-py27
    - TOXENV=django16-py26
    - TOXENV=django16-py27
    - TOXENV=django16-py32
    - TOXENV=django16-py33
    - TOXENV=django17-py27
    - TOXENV=django17-py32
    - TOXENV=django17-py33
    - TOXENV=django17-py34
    - TOXENV=django18-py27
    - TOXENV=django18-py32
    - TOXENV=django18-py33
    - TOXENV=django18-py34
    - TOXENV=django18-py35
    - TOXENV=django19-py27
    - TOXENV=django19-py34
    - TOXENV=django19-py35

install:
  - pip install coveralls tox

script:
  - tox

after_success:
  - coveralls
