language: python

python:
  - 2.6
  - 2.7

env:
  - DJANGO=Django==1.4.2
  - DJANGO=Django==1.5
  - DJANGO=Django==1.6
  - DJANGO=Django==1.7
  - DJANGO=Django==1.8

matrix:
  exclude:
    - python: 2.6
      env: DJANGO=Django==1.7
    - python: 2.6
      env: DJANGO=Django==1.8

install:
  - pip install -q $DJANGO

# command to run tests
script: python runtests.py
